name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Set up Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          nohup Xvfb :99 -screen 0 1024x768x24 &

      - name: Run linter and pytest
        env:
          DISPLAY: :99
        run: |
          make lint
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v6.0.0
        if: github.ref_name == 'main'
        env:
          DISPLAY: :99
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true